// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_square_destructor = "CgkI-ujpqeAdEAIQEA"; // <GPGSID>
        public const string achievement_medior = "CgkI-ujpqeAdEAIQDA"; // <GPGSID>
        public const string achievement_hexadeciplier = "CgkI-ujpqeAdEAIQEw"; // <GPGSID>
        public const string achievement_score_100 = "CgkI-ujpqeAdEAIQAw"; // <GPGSID>
        public const string achievement_octiplier = "CgkI-ujpqeAdEAIQEg"; // <GPGSID>
        public const string achievement_square_crasher = "CgkI-ujpqeAdEAIQDg"; // <GPGSID>
        public const string achievement_wild_one = "CgkI-ujpqeAdEAIQAQ"; // <GPGSID>
        public const string achievement_newbior = "CgkI-ujpqeAdEAIQCg"; // <GPGSID>
        public const string leaderboard_highscores = "CgkI-ujpqeAdEAIQAA"; // <GPGSID>
        public const string achievement_firestarter = "CgkI-ujpqeAdEAIQAg"; // <GPGSID>
        public const string achievement_junior = "CgkI-ujpqeAdEAIQCw"; // <GPGSID>
        public const string achievement_square_smasher = "CgkI-ujpqeAdEAIQDw"; // <GPGSID>
        public const string achievement_senior = "CgkI-ujpqeAdEAIQDQ"; // <GPGSID>
        public const string achievement_quadriplier = "CgkI-ujpqeAdEAIQEQ"; // <GPGSID>
        public const string achievement_score_1000 = "CgkI-ujpqeAdEAIQBw"; // <GPGSID>
        public const string achievement_wild_wild_wild = "CgkI-ujpqeAdEAIQCQ"; // <GPGSID>
        public const string achievement_score_500 = "CgkI-ujpqeAdEAIQBQ"; // <GPGSID>
        public const string achievement_score_200 = "CgkI-ujpqeAdEAIQBA"; // <GPGSID>
        public const string achievement_score_2000 = "CgkI-ujpqeAdEAIQCA"; // <GPGSID>

}

